//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blog: Blog;
  blogConnection: BlogConnection;
  shayari: Shayari;
  shayariConnection: ShayariConnection;
  quotes: Quotes;
  quotesConnection: QuotesConnection;
  tools: Tools;
  toolsConnection: ToolsConnection;
  prompts: Prompts;
  promptsConnection: PromptsConnection;
  stotras: Stotras;
  stotrasConnection: StotrasConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryShayariArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryShayariConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShayariFilter>;
};


export type QueryQuotesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryQuotesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuotesFilter>;
};


export type QueryToolsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryToolsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ToolsFilter>;
};


export type QueryPromptsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPromptsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PromptsFilter>;
};


export type QueryStotrasArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStotrasConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StotrasFilter>;
};

export type DocumentFilter = {
  blog?: InputMaybe<BlogFilter>;
  shayari?: InputMaybe<ShayariFilter>;
  quotes?: InputMaybe<QuotesFilter>;
  tools?: InputMaybe<ToolsFilter>;
  prompts?: InputMaybe<PromptsFilter>;
  stotras?: InputMaybe<StotrasFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blog | Shayari | Quotes | Tools | Prompts | Stotras | Folder;

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  pubDate: Scalars['String']['output'];
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  heroImage?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type Shayari = Node & Document & {
  __typename?: 'Shayari';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  pubDate?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ShayariFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  heroImage?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ShayariConnectionEdges = {
  __typename?: 'ShayariConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Shayari>;
};

export type ShayariConnection = Connection & {
  __typename?: 'ShayariConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ShayariConnectionEdges>>>;
};

export type Quotes = Node & Document & {
  __typename?: 'Quotes';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  pubDate?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type QuotesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  heroImage?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type QuotesConnectionEdges = {
  __typename?: 'QuotesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Quotes>;
};

export type QuotesConnection = Connection & {
  __typename?: 'QuotesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<QuotesConnectionEdges>>>;
};

export type Tools = Node & Document & {
  __typename?: 'Tools';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  pubDate?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ToolsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  heroImage?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ToolsConnectionEdges = {
  __typename?: 'ToolsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tools>;
};

export type ToolsConnection = Connection & {
  __typename?: 'ToolsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ToolsConnectionEdges>>>;
};

export type Prompts = Node & Document & {
  __typename?: 'Prompts';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  pubDate?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PromptsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  heroImage?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PromptsConnectionEdges = {
  __typename?: 'PromptsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Prompts>;
};

export type PromptsConnection = Connection & {
  __typename?: 'PromptsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PromptsConnectionEdges>>>;
};

export type Stotras = Node & Document & {
  __typename?: 'Stotras';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  pubDate: Scalars['String']['output'];
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StotrasFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<DatetimeFilter>;
  heroImage?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type StotrasConnectionEdges = {
  __typename?: 'StotrasConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Stotras>;
};

export type StotrasConnection = Connection & {
  __typename?: 'StotrasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StotrasConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlog: Blog;
  createBlog: Blog;
  updateShayari: Shayari;
  createShayari: Shayari;
  updateQuotes: Quotes;
  createQuotes: Quotes;
  updateTools: Tools;
  createTools: Tools;
  updatePrompts: Prompts;
  createPrompts: Prompts;
  updateStotras: Stotras;
  createStotras: Stotras;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdateShayariArgs = {
  relativePath: Scalars['String']['input'];
  params: ShayariMutation;
};


export type MutationCreateShayariArgs = {
  relativePath: Scalars['String']['input'];
  params: ShayariMutation;
};


export type MutationUpdateQuotesArgs = {
  relativePath: Scalars['String']['input'];
  params: QuotesMutation;
};


export type MutationCreateQuotesArgs = {
  relativePath: Scalars['String']['input'];
  params: QuotesMutation;
};


export type MutationUpdateToolsArgs = {
  relativePath: Scalars['String']['input'];
  params: ToolsMutation;
};


export type MutationCreateToolsArgs = {
  relativePath: Scalars['String']['input'];
  params: ToolsMutation;
};


export type MutationUpdatePromptsArgs = {
  relativePath: Scalars['String']['input'];
  params: PromptsMutation;
};


export type MutationCreatePromptsArgs = {
  relativePath: Scalars['String']['input'];
  params: PromptsMutation;
};


export type MutationUpdateStotrasArgs = {
  relativePath: Scalars['String']['input'];
  params: StotrasMutation;
};


export type MutationCreateStotrasArgs = {
  relativePath: Scalars['String']['input'];
  params: StotrasMutation;
};

export type DocumentUpdateMutation = {
  blog?: InputMaybe<BlogMutation>;
  shayari?: InputMaybe<ShayariMutation>;
  quotes?: InputMaybe<QuotesMutation>;
  tools?: InputMaybe<ToolsMutation>;
  prompts?: InputMaybe<PromptsMutation>;
  stotras?: InputMaybe<StotrasMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blog?: InputMaybe<BlogMutation>;
  shayari?: InputMaybe<ShayariMutation>;
  quotes?: InputMaybe<QuotesMutation>;
  tools?: InputMaybe<ToolsMutation>;
  prompts?: InputMaybe<PromptsMutation>;
  stotras?: InputMaybe<StotrasMutation>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ShayariMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type QuotesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ToolsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PromptsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type StotrasMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlogPartsFragment = { __typename: 'Blog', title: string, description: string, pubDate: string, heroImage?: string | null, body?: any | null };

export type ShayariPartsFragment = { __typename: 'Shayari', title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null };

export type QuotesPartsFragment = { __typename: 'Quotes', title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null };

export type ToolsPartsFragment = { __typename: 'Tools', title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null };

export type PromptsPartsFragment = { __typename: 'Prompts', title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null };

export type StotrasPartsFragment = { __typename: 'Stotras', title: string, description: string, pubDate: string, heroImage?: string | null, body?: any | null };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, description: string, pubDate: string, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, description: string, pubDate: string, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ShayariQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ShayariQuery = { __typename?: 'Query', shayari: { __typename: 'Shayari', id: string, title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ShayariConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ShayariFilter>;
}>;


export type ShayariConnectionQuery = { __typename?: 'Query', shayariConnection: { __typename?: 'ShayariConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ShayariConnectionEdges', cursor: string, node?: { __typename: 'Shayari', id: string, title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type QuotesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type QuotesQuery = { __typename?: 'Query', quotes: { __typename: 'Quotes', id: string, title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type QuotesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<QuotesFilter>;
}>;


export type QuotesConnectionQuery = { __typename?: 'Query', quotesConnection: { __typename?: 'QuotesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'QuotesConnectionEdges', cursor: string, node?: { __typename: 'Quotes', id: string, title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ToolsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ToolsQuery = { __typename?: 'Query', tools: { __typename: 'Tools', id: string, title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ToolsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ToolsFilter>;
}>;


export type ToolsConnectionQuery = { __typename?: 'Query', toolsConnection: { __typename?: 'ToolsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ToolsConnectionEdges', cursor: string, node?: { __typename: 'Tools', id: string, title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PromptsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PromptsQuery = { __typename?: 'Query', prompts: { __typename: 'Prompts', id: string, title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PromptsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PromptsFilter>;
}>;


export type PromptsConnectionQuery = { __typename?: 'Query', promptsConnection: { __typename?: 'PromptsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PromptsConnectionEdges', cursor: string, node?: { __typename: 'Prompts', id: string, title: string, description: string, pubDate?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type StotrasQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StotrasQuery = { __typename?: 'Query', stotras: { __typename: 'Stotras', id: string, title: string, description: string, pubDate: string, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type StotrasConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StotrasFilter>;
}>;


export type StotrasConnectionQuery = { __typename?: 'Query', stotrasConnection: { __typename?: 'StotrasConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StotrasConnectionEdges', cursor: string, node?: { __typename: 'Stotras', id: string, title: string, description: string, pubDate: string, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  description
  pubDate
  heroImage
  body
}
    `;
export const ShayariPartsFragmentDoc = gql`
    fragment ShayariParts on Shayari {
  __typename
  title
  description
  pubDate
  heroImage
  body
}
    `;
export const QuotesPartsFragmentDoc = gql`
    fragment QuotesParts on Quotes {
  __typename
  title
  description
  pubDate
  heroImage
  body
}
    `;
export const ToolsPartsFragmentDoc = gql`
    fragment ToolsParts on Tools {
  __typename
  title
  description
  pubDate
  heroImage
  body
}
    `;
export const PromptsPartsFragmentDoc = gql`
    fragment PromptsParts on Prompts {
  __typename
  title
  description
  pubDate
  heroImage
  body
}
    `;
export const StotrasPartsFragmentDoc = gql`
    fragment StotrasParts on Stotras {
  __typename
  title
  description
  pubDate
  heroImage
  body
}
    `;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const ShayariDocument = gql`
    query shayari($relativePath: String!) {
  shayari(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ShayariParts
  }
}
    ${ShayariPartsFragmentDoc}`;
export const ShayariConnectionDocument = gql`
    query shayariConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ShayariFilter) {
  shayariConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ShayariParts
      }
    }
  }
}
    ${ShayariPartsFragmentDoc}`;
export const QuotesDocument = gql`
    query quotes($relativePath: String!) {
  quotes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...QuotesParts
  }
}
    ${QuotesPartsFragmentDoc}`;
export const QuotesConnectionDocument = gql`
    query quotesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: QuotesFilter) {
  quotesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...QuotesParts
      }
    }
  }
}
    ${QuotesPartsFragmentDoc}`;
export const ToolsDocument = gql`
    query tools($relativePath: String!) {
  tools(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ToolsParts
  }
}
    ${ToolsPartsFragmentDoc}`;
export const ToolsConnectionDocument = gql`
    query toolsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ToolsFilter) {
  toolsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ToolsParts
      }
    }
  }
}
    ${ToolsPartsFragmentDoc}`;
export const PromptsDocument = gql`
    query prompts($relativePath: String!) {
  prompts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PromptsParts
  }
}
    ${PromptsPartsFragmentDoc}`;
export const PromptsConnectionDocument = gql`
    query promptsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PromptsFilter) {
  promptsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PromptsParts
      }
    }
  }
}
    ${PromptsPartsFragmentDoc}`;
export const StotrasDocument = gql`
    query stotras($relativePath: String!) {
  stotras(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StotrasParts
  }
}
    ${StotrasPartsFragmentDoc}`;
export const StotrasConnectionDocument = gql`
    query stotrasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StotrasFilter) {
  stotrasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StotrasParts
      }
    }
  }
}
    ${StotrasPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    shayari(variables: ShayariQueryVariables, options?: C): Promise<{data: ShayariQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShayariQueryVariables, query: string}> {
        return requester<{data: ShayariQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShayariQueryVariables, query: string}, ShayariQueryVariables>(ShayariDocument, variables, options);
      },
    shayariConnection(variables?: ShayariConnectionQueryVariables, options?: C): Promise<{data: ShayariConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShayariConnectionQueryVariables, query: string}> {
        return requester<{data: ShayariConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ShayariConnectionQueryVariables, query: string}, ShayariConnectionQueryVariables>(ShayariConnectionDocument, variables, options);
      },
    quotes(variables: QuotesQueryVariables, options?: C): Promise<{data: QuotesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuotesQueryVariables, query: string}> {
        return requester<{data: QuotesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuotesQueryVariables, query: string}, QuotesQueryVariables>(QuotesDocument, variables, options);
      },
    quotesConnection(variables?: QuotesConnectionQueryVariables, options?: C): Promise<{data: QuotesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuotesConnectionQueryVariables, query: string}> {
        return requester<{data: QuotesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: QuotesConnectionQueryVariables, query: string}, QuotesConnectionQueryVariables>(QuotesConnectionDocument, variables, options);
      },
    tools(variables: ToolsQueryVariables, options?: C): Promise<{data: ToolsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolsQueryVariables, query: string}> {
        return requester<{data: ToolsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolsQueryVariables, query: string}, ToolsQueryVariables>(ToolsDocument, variables, options);
      },
    toolsConnection(variables?: ToolsConnectionQueryVariables, options?: C): Promise<{data: ToolsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolsConnectionQueryVariables, query: string}> {
        return requester<{data: ToolsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolsConnectionQueryVariables, query: string}, ToolsConnectionQueryVariables>(ToolsConnectionDocument, variables, options);
      },
    prompts(variables: PromptsQueryVariables, options?: C): Promise<{data: PromptsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PromptsQueryVariables, query: string}> {
        return requester<{data: PromptsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PromptsQueryVariables, query: string}, PromptsQueryVariables>(PromptsDocument, variables, options);
      },
    promptsConnection(variables?: PromptsConnectionQueryVariables, options?: C): Promise<{data: PromptsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PromptsConnectionQueryVariables, query: string}> {
        return requester<{data: PromptsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PromptsConnectionQueryVariables, query: string}, PromptsConnectionQueryVariables>(PromptsConnectionDocument, variables, options);
      },
    stotras(variables: StotrasQueryVariables, options?: C): Promise<{data: StotrasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StotrasQueryVariables, query: string}> {
        return requester<{data: StotrasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StotrasQueryVariables, query: string}, StotrasQueryVariables>(StotrasDocument, variables, options);
      },
    stotrasConnection(variables?: StotrasConnectionQueryVariables, options?: C): Promise<{data: StotrasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StotrasConnectionQueryVariables, query: string}> {
        return requester<{data: StotrasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StotrasConnectionQueryVariables, query: string}, StotrasConnectionQueryVariables>(StotrasConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/d3cb431b-ec2b-4028-aeca-786050418f67/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  